[application]
asset_dir = "assets"

[web.app]

# HTML title tag content
title = "ferlora"

# include `assets` in web platform
[web.resource]

# Additional CSS style files
style = []

# Additional JavaScript files
script = []

[web.resource.dev]

# Javascript code file
# serve: [dev-server] only
script = []

# [[web.proxy]]
# backend = "http://localhost:8000/api/"


[web.watcher]
watch_path = ["src", "public", "assets/content/home.html"]

